### ISSUE TITLE
试了下非常好用

### ISSUE THREAD

**Issue by YUIIUY** [tzwsoho/NEC_Crawler#2]
但还是希望加入需要登录付费的漫画的下载功能...

**Comment by tzwsoho** [comment]
谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈

**Comment by YUIIUY** [comment]
> 
> 
> 谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈

哈哈...回复这么快...我也要感谢你的作品...冬天注意保暖哦...

**Comment by tzwsoho** [comment]
> > 谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈
> 
> 哈哈...回复这么快...我也要感谢你的作品...冬天注意保暖哦...

已经加上了登录下载功能，不过我没开通会员没办法测试，要是你有会员可以帮忙测试下

**Comment by YUIIUY** [comment]
> 
> 
> > > 谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈
> > 
> > 
> > 哈哈...回复这么快...我也要感谢你的作品...冬天注意保暖哦...
> 
> 已经加上了登录下载功能，不过我没开通会员没办法测试，要是你有会员可以帮忙测试下

你好，我搞了个测试账号来使用钻石购买了两章付费章节，但新版本爬虫扫描二维码登录后依然只爬了前面的免费章节...我把账号密码发到你邮箱你看看吧...

**Comment by tzwsoho** [comment]
> > > > 谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈
> > > 
> > > 
> > > 哈哈...回复这么快...我也要感谢你的作品...冬天注意保暖哦...
> > 
> > 
> > 已经加上了登录下载功能，不过我没开通会员没办法测试，要是你有会员可以帮忙测试下
> 
> 你好，我搞了个测试账号来使用钻石购买了两章付费章节，但新版本爬虫扫描二维码登录后依然只爬了前面的免费章节...我把账号密码发到你邮箱你看看吧...

问题已解决，不过有时登录后还是下载不到付费章节，重试一次即可

**Comment by YUIIUY** [comment]
> 
> 
> > > > > 谢谢评价，我在做这爬虫时还有很多漫画都还没收费，所以也没做这功能。最近天气有点冷，人也有点懒，回头我有时间看再加上哈
> > > > 
> > > > 
> > > > 哈哈...回复这么快...我也要感谢你的作品...冬天注意保暖哦...
> > > 
> > > 
> > > 已经加上了登录下载功能，不过我没开通会员没办法测试，要是你有会员可以帮忙测试下
> > 
> > 
> > 你好，我搞了个测试账号来使用钻石购买了两章付费章节，但新版本爬虫扫描二维码登录后依然只爬了前面的免费章节...我把账号密码发到你邮箱你看看吧...
> 
> 问题已解决，不过有时登录后还是下载不到付费章节，重试一次即可

十分感谢！新版本已能正常抓取付费章节...
而且这版图片下载进度除百分比外增加了图片数量显示也很实用...
终于可以收藏想要的电子版漫画了XD...
