### ISSUE TITLE
同名章节下载&图片格式问题

### ISSUE THREAD

**Issue by YUIIUY** [tzwsoho/NEC_Crawler#3]
通过使用博主写的这个爬虫配合从某宝买的数个带砖石券账号，我已经如愿爬完了想要的那部付费漫画的全部主要章节，但是我发现似乎是因为有几个章节是同名的原因，并未能正常下载（有三个“特别收录 初期短篇”，使用爬虫只下载了第一个，有四个“特别短篇”，但也只能下载第一个...）

本来我想着只有六章节了，这种同名章节的情况应该也比较少见，就不忍心再来麻烦你了，想从网页手动扒，结果保存下来的文件居然不能查看...查了下才知道原来网易漫画提供webp与jpg两种格式，通过比较我发现同一页webp格式的图片清晰度高于之前爬虫爬取的jpg格式的...于是这里又产生了另一个想法：能不能在config.json中提供格式选择的选项？jpg格式的图片方便制作成kindle电子书，webp格式的图片虽然不能直接制作电子书，但画质上更适合收藏用...

之前通过邮件发给你的测试用的账号正好【不好意思换号换来换去我搞昏了...解锁了相关章节的是另一个账号...已通过邮件发送...】解锁了涉及问题的其中几个章节...博主有时间的话可以再登录账号看看...谢谢了...

**Comment by tzwsoho** [comment]
你说的两个问题已经处理了

**Comment by YUIIUY** [comment]
> 
> 
> 你说的两个问题已经处理了

卧槽神速啊...谢谢大佬...
